### ISSUE TITLE
Why did you move $user variable to $_user in templates?

### ISSUE THREAD

**Issue by vanam** [contributte/webapp-skeleton#204]
Hi @f3l1x ,
why did you move $user variable to $_user in templates (https://github.com/contributte/webapp-skeleton/blob/8b4ad639bd010799fff94609edac80b3454e2b83/app/model/Latte/TemplateFactory.php)?

It took me few minutes to find out why it is inconsistent with Nette documentation. I guess I am guilty of misusing this variable. Could you explain how we should use it properly and what was your intention?

Thx

**Comment by f3l1x** [comment]
Hi @vanam. It's because of foreach and other parts where I want to use `{foreach $users a $user}`, but normally I can't. I prefer to override security user to `$_user`.

**Comment by vanam** [comment]
Ok. There should be some kind of warning so people don't fall into the same pit as I did.

**Comment by f3l1x** [comment]
Can you rewrite something?
