### ISSUE TITLE
Path for running fixtures

### ISSUE THREAD

**Issue by darkWolf-PR** [contributte/webapp-skeleton#336]
I´ve used skeleton for web app upgrade, but when trying to run Fixtures(php bin/console doctrine:fixtures:load), I keep getting this:
```

In LoadDataFixturesCommand.php line 121:

  Could not find any fixtures to load in:
```
  
  
While running php bin/console migrations:migrate normally builds DB tables. Dirs are from the skeleton - root/db/Migrations and root/db/Fixtures
 
in config:

```
nettrine.migrations:
        directory: %rootDir%/db/Migrations

```
and

```
paths:
        - %rootDir%/db/Fixtures
```
        
I just don´t understand where´s the problem. Same folders, same path dir in config?!?!? And the fixtures are there, same AbstractFixture and UserFixters, just with changed credentials. I´m working on Windows, so I would guess it has something to do with Win path, but I can´t find out how to solve it.

**Comment by f3l1x** [comment]
Hmmm. I am not sure either.

**Comment by darkWolf-PR** [comment]
Ok, my fault. I forget to try checking version/run composer update - problem was repaired here - https://github.com/nettrine/fixtures/commit/56accd28d40e6be410d8ebb147d60c45e257eef7
