### ISSUE TITLE
Could not find driver

### ISSUE THREAD

**Issue by krajcikondra** [contributte/webapp-skeleton#391]
Hi,

When I run project in docker by command **docker-compose up** and run **bin/console migrations:diff** in nette-project_php container, I get followring error:

***
In ExceptionConverter.php line 91:
An exception occurred in the driver: could not find driver  
                                                              
In Exception.php line 30:
could not find driver  
                         

In Driver.php line 28:
could not find driver
***

I tried to install **apt-get install php 8.0-pgsql** but the problem remains

**Comment by f3l1x** [comment]
Hi @krajcikondra. Thanks for report, I will take a look.

**Comment by petrparolek** [comment]
I will take a look

**Comment by petrparolek** [comment]
It works  on latest revision of this repo daadd22cec4f5a935478a34a1b37c61535d003ce

1) `git clone git clone https://github.com/contributte/webapp-skeleton.git`
2] `docker-compose up .-d`

![obrazek](https://user-images.githubusercontent.com/6066243/207454085-baed3188-b5c7-4c4b-b8f8-de93bb741b29.png)

**Comment by krajcikondra** [comment]
I am sorry, It works after restart container.
