### ISSUE TITLE
Nette\DI\InvalidConfigurationException

### ISSUE THREAD

**Issue by lub-or** [contributte/webapp-skeleton#500]
Zdravím. Vůbec se mi projekt nedaří rozbehnout. Chybová hláška:

Nette\DI\InvalidConfigurationException
Unexpected item 'contributte.console › lazy

Nevíte jak na to?

**Comment by f3l1x** [comment]
Ahoj, ono to pise tu hlasku dobre, mrkni jestli tam je nekde v neon configu `lazy` u console a odstran to.
